---
- name: check vault-plugin-secrets-oauthapp version
  ansible.builtin.slurp:
    src: "{{ vault_dir }}/vault-plugin-secrets-oauthapp-version"
  register: vault_plugin_secrets_oauthapp_current_version
  changed_when: false
  ignore_errors: true
  tags:
    - vault-plugins

- name: install vault-plugin-secrets-oauthapp
  when: vault_plugin_secrets_oauthapp_current_version.failed or vault_plugin_secrets_oauthapp_current_version['content'] | b64decode != vault_plugin_secrets_oauthapp_file
  tags:
    - vault-plugins
  block:
    - name: download archive
      ansible.builtin.get_url:
        url: "{{ vault_plugin_secrets_oauthapp_archive_url }}"
        dest: /tmp/{{ vault_plugin_secrets_oauthapp_archive }}
        checksum: sha256:{{ vault_plugin_secrets_oauthapp_checksum_archive_url }}
        mode: "0700"

    - name: extract archive
      ansible.builtin.unarchive:
        src: /tmp/{{ vault_plugin_secrets_oauthapp_archive }}
        dest: /tmp
        remote_src: true

    - name: file
      ansible.builtin.copy:
        src: /tmp/{{ vault_plugin_secrets_oauthapp_file }}
        dest: "{{ vault_dir }}/plugins/vault-plugin-secrets-oauthapp"
        owner: vault
        group: vault
        mode: "0700"
        setype: bin_t
        seuser: system_u
        remote_src: true

    - name: cleanup archive
      ansible.builtin.file:
        path: /tmp/{{ vault_plugin_secrets_oauthapp_archive }}
        state: absent

    - name: cleanup file
      ansible.builtin.file:
        path: /tmp/{{ vault_plugin_secrets_oauthapp_file }}
        state: absent

    - name: give the executable the ability to use the mlock syscall
      community.general.capabilities:
        path: "{{ vault_dir }}/plugins/vault-plugin-secrets-oauthapp"
        capability: cap_ipc_lock=+ep
        state: present

    - name: write version
      ansible.builtin.copy:
        content: "{{ vault_plugin_secrets_oauthapp_file }}"
        dest: "{{ vault_dir }}/vault-plugin-secrets-oauthapp-version"
        owner: root
        group: root
        mode: "0644"
