---

- name: check vault-plugin-secrets-github version
  ansible.builtin.slurp:
    src: "{{ vault_dir }}/vault-plugin-secrets-github-version"
  register: vault_plugin_secrets_github_current_version
  changed_when: false
  ignore_errors: true

- name: install vault-plugin-secrets-github
  when: vault_plugin_secrets_github_current_version.failed or vault_plugin_secrets_github_current_version['content'] | b64decode != vault_plugin_secrets_github_file
  block:
    - name: download
      ansible.builtin.get_url:
        url: "{{ vault_plugin_secrets_github_file_url }}"
        dest: "{{ vault_dir }}/plugins/vault-plugin-secrets-github"
        checksum: "sha256:{{ vault_plugin_secrets_github_checksum_file_url }}"
        mode: 0700
      changed_when: false

    - name: chcon binary
      ansible.builtin.file:
        path: "{{ vault_dir }}/plugins/vault-plugin-secrets-github"
        owner: vault
        group: vault
        mode: 0700
        setype: bin_t
        seuser: system_u

    - name: give the executable the ability to use the mlock syscall
      community.general.capabilities:
        path: "{{ vault_dir }}/plugins/vault-plugin-secrets-github"
        capability: cap_ipc_lock=+ep
        state: present

    - name: write version
      ansible.builtin.copy:
        content: "{{ vault_plugin_secrets_github_file }}"
        dest: "{{ vault_dir }}/vault-plugin-secrets-github-version"
        owner: root
        group: root
        mode: '0644'
